name: LGTM list

on:
  workflow_dispatch:
  pull_request:
    paths: 'LGTM/**'
  push:
    paths: 'LGTM/**'

jobs:
  create_list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create LGTM list
        run: ./bin/make_lgtm.sh
      - name: Commit & Push
        run: |
          git config user.name yoshi389111
          git config user.email yoshi.389111@gmail.com
          git add -A .
          if git commit -m "create LGTM list"; then
            git push
          fi
